#!/bin/sh
# Использование RAM в % по /proc/meminfo.
awk '
/MemTotal:/  { total = $2 }
/MemAvailable:/ { avail = $2 }
END {
    if (total > 0)
        printf "%d", (total - avail) * 100 / total
    else
        print 0
}' /proc/meminfo
